name: format_taxonomy_sintax
description: Formats a reference database for SINTAX
keywords:
  - sintax
  - vsearch
  - taxonomy
  - database
tools:
  - bash:
      description: The GNU Bourne-Again SHell
      homepage: https://www.gnu.org/software/bash/
      licence:
        - GPL-3.0-or-later
      identifier: ""
input:
  - database:
      type: file
      description: Reference database files
output:
  db:
    - sintaxdb.fa.gz:
        type: file
        description: Reference sequences with SINTAX taxonomy (FASTA)
        pattern: sintaxdb.fa.gz
  ref_tax_info:
    - ref_taxonomy_sintax.txt:
        type: file
        description: Reference database provenance
        pattern: ref_taxonomy_sintax.txt
  versions_format_taxonomy_sintax:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@emnilsson"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
