name: sidle_tablerecon
description: Reconstructs feature counts across regions with Sidle
keywords:
  - sidle
  - multi-region
  - reconstruction
  - feature table
tools:
  - q2-sidle:
      description: QIIME 2 implementation of SMURF, reconstructing full-length marker genes from multiple amplified regions
      homepage: https://github.com/jwdebelius/q2-sidle
      licence:
        - BSD-3-Clause
      identifier: ""
input:
  - region:
      type: string
      description: Region identifiers
  - table:
      type: file
      description: Regional feature table artifacts
  - aligned_map:
      type: file
      description: Alignment map artifacts
  - reconstruction_map:
      type: file
      description: Reconstruction map artifact
  - reconstruction_summary:
      type: file
      description: Reconstruction summary artifact
output:
  qza:
    - reconstruction_table.qza:
        type: file
        description: QIIME2 feature table artifact
        pattern: reconstruction_table.qza
  exported:
    - reconstruction_table/*:
        type: file
        description: Exported reconstructed feature table
        pattern: reconstruction_table/*
  biom:
    - reconstructed_feature-table.biom:
        type: file
        description: Reconstructed feature table (BIOM)
        pattern: reconstructed_feature-table.biom
  tsv:
    - reconstructed_feature-table.tsv:
        type: file
        description: Reconstructed feature table (TSV)
        pattern: reconstructed_feature-table.tsv
  versions_sidle_tablerecon:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
