name: sidle_filttax
description: Merges Sidle reconstructed taxonomy with abundances
keywords:
  - sidle
  - multi-region
  - taxonomy
tools:
  - q2-sidle:
      description: QIIME 2 implementation of SMURF, reconstructing full-length marker genes from multiple amplified regions
      homepage: https://github.com/jwdebelius/q2-sidle
      licence:
        - BSD-3-Clause
      identifier: ""
input:
  - table_tofilter:
      type: file
      description: Reconstructed taxonomy table (TSV)
  - table_ref:
      type: file
      description: Reconstructed feature table (TSV)
output:
  filtered:
    - reconstructed_taxonomy.tsv:
        type: file
        description: Taxonomy of reconstructed features (TSV)
        pattern: reconstructed_taxonomy.tsv
  merged:
    - reconstructed_merged.tsv:
        type: file
        description: Reconstructed features with taxonomy and abundances (TSV)
        pattern: reconstructed_merged.tsv
  versions_sidle_filttax:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
