name: qiime2_barplot
description: Creates taxonomic barplots with QIIME2
keywords:
  - qiime2
  - barplot
  - taxonomy
tools:
  - qiime2:
      description: Microbiome multi-omics data science platform
      homepage: https://qiime2.org
      licence:
        - BSD-3-Clause
      identifier: biotools:qiime2
input:
  - metadata:
      type: file
      description: Sample metadata table (TSV)
  - table:
      type: file
      description: QIIME2 feature table artifact
  - taxonomy:
      type: file
      description: QIIME2 taxonomy artifact
  - setting:
      type: boolean
      description: Whether to suffix the output folder with the table name
output:
  folder:
    - barplot${suffix}/*:
        type: file
        description: Exported barplot
        pattern: barplot${suffix}/*
  versions_qiime2_barplot:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
