name: format_fastainput
description: Normalises user-supplied ASV sequences for the pipeline
keywords:
  - fasta
  - format
  - input
tools:
  - sed:
      description: GNU stream editor
      homepage: https://www.gnu.org/software/sed/
      licence:
        - GPL-3.0-or-later
      identifier: ""
input:
  - fastain:
      type: file
      description: Input sequences (FASTA)
output:
  fasta:
    - input.mod.fasta:
        type: file
        description: Normalised sequences (FASTA)
        pattern: input.mod.fasta
  versions_format_fastainput:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@jtangrot"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
