name: sidle_dbextract
description: Extracts regional k-mers from a reference database for Sidle
keywords:
  - sidle
  - multi-region
  - database
tools:
  - q2-sidle:
      description: QIIME 2 implementation of SMURF, reconstructing full-length marker genes from multiple amplified regions
      homepage: https://github.com/jwdebelius/q2-sidle
      licence:
        - BSD-3-Clause
      identifier: ""
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information, e.g. [ id:'test' ]
    - table:
        type: file
        description: QIIME2 feature table artifact
    - seq:
        type: file
        description: QIIME2 representative sequences artifact
    - db_seq:
        type: file
        description: Reference sequences artifact
    - db_tax:
        type: file
        description: Reference taxonomy artifact
output:
  kmers:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - db_*_kmers.qza:
          type: file
          description: Regional k-mers artifact
          pattern: db_*_kmers.qza
  kmer_map:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - db_*_map.qza:
          type: file
          description: K-mer map artifact
          pattern: db_*_map.qza
  versions_sidle_dbextract:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
