name: dada2_err
description: Learns DADA2 error rates
keywords:
  - dada2
  - error model
  - amplicon
tools:
  - dada2:
      description: Infers exact amplicon sequence variants (ASVs) from high-throughput amplicon sequencing data
      homepage: https://bioconductor.org/packages/dada2
      documentation: https://benjjneb.github.io/dada2/
      licence:
        - LGPL-2
      identifier: biotools:dada2
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information, e.g. [ id:'test' ]
    - reads:
        type: file
        description: Filtered reads (FASTQ)
output:
  errormodel:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - "*.err.rds":
          type: file
          description: DADA2 error models (RDS)
          pattern: "*.err.rds"
  pdf:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - "*.err.pdf":
          type: file
          description: Error model plots (PDF)
          pattern: "*.err.pdf"
  svg:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - "*.err.svg":
          type: file
          description: Error model plots (SVG)
          pattern: "*.err.svg"
  log:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - "*.err.log":
          type: file
          description: Log file
          pattern: "*.err.log"
  convergence:
    - - meta:
          type: map
          description: Groovy Map containing sample information, e.g. [ id:'test' ]
      - "*.err.convergence.txt":
          type: file
          description: Convergence of the error model estimation
          pattern: "*.err.convergence.txt"
  versions_dada2_err:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
  args:
    - "*.args.txt":
        type: file
        description: Arguments passed to the tool, for the summary report
        pattern: "*.args.txt"
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
