---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-dada2=1.38.0
  - conda-forge::r-base=4.5.2
  - conda-forge::r-digest=0.6.39
  - conda-forge::tbb=2022.3.0
