name: qiime2_tree
description: Builds a rooted phylogenetic tree of ASVs with QIIME2
keywords:
  - qiime2
  - phylogeny
  - tree
  - mafft
  - fasttree
tools:
  - qiime2:
      description: Microbiome multi-omics data science platform
      homepage: https://qiime2.org
      licence:
        - BSD-3-Clause
      identifier: biotools:qiime2
input:
  - repseq:
      type: file
      description: QIIME2 representative sequences artifact
output:
  qza:
    - rooted-tree.qza:
        type: file
        description: QIIME2 rooted tree artifact
        pattern: rooted-tree.qza
  nwk:
    - tree.nwk:
        type: file
        description: Rooted tree (Newick)
        pattern: tree.nwk
  versions_qiime2_tree:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
authors:
  - "@d4straub"
maintainers:
  - "@d4straub"
  - "@erikrikarddaniel"
